### ISSUE TITLE
尝试了一下，pod install 后报错

### ISSUE THREAD

**Issue by sxiaojian88** [WeijunDeng/AutoBuildCache#1]
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `product_type' for #<Xcodeproj::Project::Object::PBXAggregateTarget:0x00007fd9bb352720>
Did you mean?  product_name

/Users/sxiaojian/ios/auto_build_cache.rb:349:in `getProductNameForTarget'
/Users/sxiaojian/ios/auto_build_cache.rb:277:in `canCacheTarget'
/Users/sxiaojian/ios/auto_build_cache.rb:404:in `block (2 levels) in checkCache'
/Users/sxiaojian/ios/auto_build_cache.rb:403:in `each'
/Users/sxiaojian/ios/auto_build_cache.rb:403:in `block in checkCache'
/Users/sxiaojian/ios/auto_build_cache.rb:402:in `each'
/Users/sxiaojian/ios/auto_build_cache.rb:402:in `checkCache'
/Users/sxiaojian/ios/auto_build_cache.rb:631:in `autoBuildCache'
/Users/sxiaojian/ios/Podfile:309:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:836:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:824:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:823:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:309:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:290:in `create_and_save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:281:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:159:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

**Comment by WeijunDeng** [comment]
不好意思，脚本目前只在pod 1.5.3 和pod 1.3.1 测试过。pod 新版本更新了一些api，我迟点兼容一下

**Comment by sxiaojian88** [comment]
我查了下，是不同类型的target导致的，一种是NativeTarget ，另一种是AggregateTarget

**Comment by sxiaojian88** [comment]
我尝试去debug cocoapods install 和 post install 的过程，但是一直debug不成功，用的rubymine的ide，直接run可以成功，但是一debug就失败，有什么更好的工具或者办法吗？

**Comment by WeijunDeng** [comment]
@sxiaojian88 我都是直接跑脚本+打印的哈哈，没调试过呢

**Comment by WeijunDeng** [comment]
@sxiaojian88 我猜测你debug podfile的话，可能有些require需要补一下？对了，现在你这边能跑我这个最新的脚本了吗

**Comment by sxiaojian88** [comment]
中午给回复，我先忙会别的

**Comment by sxiaojian88** [comment]
没有问题
