### ISSUE TITLE
请教两个问题😁

### ISSUE THREAD

**Issue by ZsIsMe** [WeijunDeng/AutoBuildCache#3]
1.  缓存脚本是写在 podfile 里面的,如果每次打包cocospods没改变,不执行 pod install(update),只是git pull 拉取业务代码,还能用这个做缓存么?  
2. 请问怎么在 pod 里面定义打包机器呢?

非常感谢!

**Comment by WeijunDeng** [comment]
1. 理论上可以，但要改一下脚本，然后加到打包脚本里
2. 比如说，打包机器的打包路径跟开发者很可能是不一样的，如/Users/admin/workspace/iOS

**Comment by ZsIsMe** [comment]
感谢你的回复! 也就是说,对于现在的AutoBuildCache来说,每次打包前都应该 pod install(update)一下?

**Comment by WeijunDeng** [comment]
对的
