### ISSUE TITLE
关于脚本逻辑

### ISSUE THREAD

**Issue by billxie1988** [WeijunDeng/AutoBuildCache#4]
if content.include? '$PODS_CONFIGURATION_BUILD_DIR'
            addition = addition + '$PODS_CONFIGURATION_BUILD_DIR'
        elsif content.include? '${PODS_CONFIGURATION_BUILD_DIR}'
            addition = addition + '${PODS_CONFIGURATION_BUILD_DIR}'
        else
            addition = addition + '${PODS_CONFIGURATION_BUILD_DIR}'
            #next，如果进入next逻辑 永远都不会注入到sh文件里。
        end

**Comment by WeijunDeng** [comment]
请问您有遇到这种情况吗

**Comment by billxie1988** [comment]
是的 我的组件壳工程里 没有include PODS_CONFIGURATION_BUILD_DIR

**Comment by WeijunDeng** [comment]
好的，已更新。
