### ISSUE TITLE
swift混编支持

### ISSUE THREAD

**Issue by sunzhongliangde** [WeijunDeng/AutoBuildCache#5]
项目中如果swift混编，打包的时候就报错：
`fatal error: module map file '/Users/admin/Library/Developer/Xcode/DerivedData/xxx-daesdalcakvokxfakgpljpmmzcay/Build/Intermediates.noindex/ArchiveIntermediates/xxx/BuildProductsPath/Release-iphoneos/lottie-ios/Lottie.modulemap' not found
1 error generated.`

纯OC项目是可以执行成功的, 另外在脚本当中把这个库屏蔽掉也是可以执行成功的。
`return false if productName.include?('lottie')`

**Comment by gshe** [comment]
你是不是使用 shell 脚本，通过xcodebuild 命令行进行编译？
如果是，把参数  CONFIGURATION_TEMP_DIR=${xxxx} 移除掉就OK了
